"""empty message

Revision ID: 1dc109cecc3d
Revises: 
Create Date: 2022-05-30 16:59:54.186906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc109cecc3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('singer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('singer_name', sa.String(), nullable=True),
    sa.Column('singer_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_name', sa.String(), nullable=True),
    sa.Column('music_img', sa.String(), nullable=True),
    sa.Column('music_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_owner'], ['singer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_name', sa.String(), nullable=True),
    sa.Column('album_owner', sa.Integer(), nullable=True),
    sa.Column('album_music', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_music'], ['music.id'], ),
    sa.ForeignKeyConstraint(['album_owner'], ['singer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_type', sa.String(), nullable=True),
    sa.Column('catygory_music', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catygory_music'], ['music.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gengre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gener_music', sa.Integer(), nullable=True),
    sa.Column('genere_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gener_music'], ['music.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gengre')
    op.drop_table('category')
    op.drop_table('album')
    op.drop_table('music')
    op.drop_table('users')
    op.drop_table('singer')
    # ### end Alembic commands ###
